// there are four different keywords used in exception handling. These are:
try
catch
finally
throw



try {

	// code that may throw the exception

} catch (e: SomeException) {
	// code that handle s the exception
}



val srt = getNumber("10")		// the variable str is getting the int value of "10"

// nested try catch blocks are also possible

// finally block is always executes whether exception is handled or not



